# Generated by Django 2.2.6 on 2021-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210225_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emoji',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='emoji',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
