# Generated by Django 2.2.6 on 2021-04-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210401_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='post',
            name='emoji',
        ),
    ]
